# Generated by Django 3.2.8 on 2021-10-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Film', models.CharField(max_length=100)),
                ('People', models.CharField(max_length=100)),
            ],
        ),
    ]
