# Generated by Django 3.2.8 on 2021-10-08 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movies',
            new_name='MyMovies',
        ),
    ]
