# Generated by Django 3.2.8 on 2021-10-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0002_rename_movies_mymovies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymovies',
            old_name='People',
            new_name='person1',
        ),
        migrations.AddField(
            model_name='mymovies',
            name='person2',
            field=models.CharField(default='nn', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mymovies',
            name='person3',
            field=models.CharField(default='nn', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mymovies',
            name='person4',
            field=models.CharField(default='nn', max_length=100),
            preserve_default=False,
        ),
    ]
