# Generated by Django 3.2.8 on 2021-10-08 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0003_auto_20211008_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymovies',
            name='Film',
        ),
    ]
