# Generated by Django 3.2.8 on 2021-10-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0004_remove_mymovies_film'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peaople',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person1', models.CharField(max_length=100)),
                ('person2', models.CharField(max_length=100)),
                ('person3', models.CharField(max_length=100)),
                ('person4', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='mymovies',
            old_name='person1',
            new_name='Film1',
        ),
        migrations.RenameField(
            model_name='mymovies',
            old_name='person2',
            new_name='Film2',
        ),
        migrations.RenameField(
            model_name='mymovies',
            old_name='person3',
            new_name='Film3',
        ),
        migrations.RemoveField(
            model_name='mymovies',
            name='person4',
        ),
    ]
