# Generated by Django 3.2.8 on 2021-10-08 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0006_peaople_mymovies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peaople',
            name='MyMovies',
        ),
    ]
