# Generated by Django 3.2.8 on 2021-10-08 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0009_auto_20211008_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=100)),
                ('MyMovies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movies.mymovies')),
            ],
        ),
    ]
