# Generated by Django 3.2.8 on 2021-10-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0010_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='amount',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
