# Generated by Django 3.2.8 on 2021-10-08 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0011_people_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='person',
        ),
    ]
