# Generated by Django 3.2.8 on 2021-10-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0012_remove_people_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='amount',
        ),
        migrations.AddField(
            model_name='people',
            name='person',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
    ]
