# Generated by Django 3.2.8 on 2021-10-08 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0013_auto_20211008_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='MyMovies',
            new_name='mymovies',
        ),
        migrations.AddField(
            model_name='mymovies',
            name='date',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mymovies',
            name='type',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
    ]
