# Generated by Django 3.2.8 on 2021-10-08 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0014_auto_20211009_0040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymovies',
            name='date',
        ),
        migrations.RemoveField(
            model_name='mymovies',
            name='type',
        ),
    ]
