# Generated by Django 3.2.8 on 2021-10-09 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0015_auto_20211009_0045'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyMovies',
            new_name='Films',
        ),
        migrations.RenameField(
            model_name='people',
            old_name='mymovies',
            new_name='films',
        ),
    ]
