# Generated by Django 3.2.8 on 2021-10-09 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0016_auto_20211009_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='films',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person', to='Movies.films'),
        ),
    ]
